name: Build

on:
  workflow_dispatch:
  push:
    branches: ['**']
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x with caching
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install --immutable
      - name: Build
        uses: borales/actions-yarn@v5
        with:
          cmd: build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
