name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x with caching
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install --immutable
      - name: Build
        uses: borales/actions-yarn@v5
        with:
          cmd: test --coverage
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x with caching
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install --immutable
      - name: Build
        uses: borales/actions-yarn@v5
        with:
          cmd: build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_KEY}}
